build_from:
  aarch64: ghcr.io/goauthentik/server:2024.10.3
  amd64: ghcr.io/goauthentik/server:2024.10.3
  armv7: ghcr.io/goauthentik/server:2024.10.3
labels:
  org.opencontainers.image.title: "Authentik"
  org.opencontainers.image.description: "Self-hosted identity provider"
  org.opencontainers.image.source: "https://github.com/yourusername/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
