build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
labels:
  org.opencontainers.image.title: "Authentik"
  org.opencontainers.image.description: "Self-hosted identity provider"
  org.opencontainers.image.source: "https://github.com/yourusername/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  AUTHENTIK_VERSION: "2024.10.3"
