build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:15.0.8
  amd64: ghcr.io/hassio-addons/base/amd64:15.0.8
  armhf: ghcr.io/hassio-addons/base/armhf:15.0.8
  armv7: ghcr.io/hassio-addons/base/armv7:15.0.8
  i386: ghcr.io/hassio-addons/base/i386:15.0.8
args: {}
labels:
  org.opencontainers.image.title: Monica Personal CRM
  org.opencontainers.image.description: Personal Relationship Management - Remember everything about your friends, family and business relationships
  org.opencontainers.image.source: https://github.com/TheDuke427/gaseous
  org.opencontainers.image.licenses: AGPL-3.0
